name: Build Javolution Extended (J2SE 1.4+)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install JDK 5
      run: |
        chmod +x lib/jdk-1_5_0_22-linux-amd64-direct.bin
        ./lib/jdk-1_5_0_22-linux-amd64-direct.bin

    - name: Build Javolution Extended
      run: ant -Djavac.executable=$(pwd)/jdk1.5.0_22/bin/javac -Djavadoc.executable=$(pwd)/jdk1.5.0_22/bin/javadoc 1.4

    - uses: actions/upload-artifact@v5
      with:
        name: Javolution v5.7.5 (J2SE 1.4+)
        path: target/javolution-5.7.5.jar
        compression-level: 9